name: bitmap_plus
description: Bitmap is a fast and minimalistic lib that heelps you to manipulate image on Flutter apps.
version: 0.2.1
homepage: https://github.com/BrianTran24/bitmap_plus
topics: [image, image-processing, ffi]

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.9"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.bitmap
        pluginClass: BitmapPlugin
      ios:
        pluginClass: BitmapPlugin
